name: Build, Test, and Deploy

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        node-version: 12.x

    - name: Install
      uses: bahmutov/npm-install@v1

    - name: test
      run: |
        npm test
      env:
        CI: true

    - name: Prepare and deploy
      run: |
        npm run deploy -- --name="Swimlane" --email="swimlane-devops@swimlane.com"
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
